spring:
  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:pictgram
#    username: sa
#    password: 
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/pictgram
    username: ${psql.user}
    password: ${psql.password}
    
  h2:
    console:
      enabled: true

  mvc:
    hiddenmethod:
      filter:
        enabled: true
        
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      
image:
  local: true
